### PR TITLE
Update Brute.sh

### PR DESCRIPTION
**Pull request by rubencm**

### CODE REVIEW

**Comment by rubencm** [comment]
It should work now

**Comment by Gh005t** [comment]
Still not working 
line 32: syntax error: unexpected end of file  :-(

**Comment by Gh005t** [comment]
still not working

line 32: syntax error: unexpected end of file

**Comment by Gh005t** [comment]
its working sorry for the comment i missed type some of the line "your code
is working thanks"

**Comment by Gh005t** [comment]
thanks rubencm

**Comment by rubencm** [comment]
:thumbsup:

**Pull request merged**
